# ___                 __            
#(_   _ _ _ /|/|   _// _)/  _ / _ _ 
#/ ()/ (/(-/   |()(//(_)(()( /((-/  
#     _/                            
#
# version 1.0.2-BETA
# by Jul1an_K

blockForge: false
blockForgeKickMessage: '&cPlease remove Forge to join.'

blockLabyMod: true

blockMods: true
blockedMods:
- JourneyMap

blockedModKickMessage: '&cPlease remove the following mod(s) to join:'
blockedModListingFormat: '&8- &c%mod_name% &8(&c%mod_version%&8)'